### ISSUE TITLE
Error when execute run_exp_main.sh

### ISSUE THREAD

**Issue by Hyaloid** [uwplse/tensat#7]
When I was about to execute run_exp_main.sh, I got an error below:
```
error: `failed to run custom build command for `tensat v0.1.0 (/usr/tensat)`

Caused by:
  process didn't exit successfully: `/usr/tensat/target/release/build/tensat-b9344c7211bdc88f/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-search=/opt/conda/lib
  cargo:rustc-link-lib=protobuf
  cargo:rustc-link-search=/usr/local/lib
  cargo:rustc-link-lib=taso_runtime
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  wrapper.h:1:10: fatal error: '../include/taso/ops.h' file not found
  wrapper.h:1:10: fatal error: '../include/taso/ops.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', build.rs:35:10
  stack backtrace:
     0:     0x558247ee1d9d - std::backtrace_rs::backtrace::libunwind::trace::h22893a5306c091b4
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x558247ee1d9d - std::backtrace_rs::backtrace::trace_unsynchronized::h29c3bc6f9e91819d
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x558247ee1d9d - std::sys_common::backtrace::_print_fmt::he497d8a0ec903793
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
     3:     0x558247ee1d9d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
     4:     0x558247f0693c - core::fmt::write::hba4337c43d992f49
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
     5:     0x558247edeb91 - std::io::Write::write_fmt::heb73de6e02cfabed
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
     6:     0x558247ee3ad5 - std::sys_common::backtrace::_print::h63c8b24acdd8e8ce
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
     7:     0x558247ee3ad5 - std::sys_common::backtrace::print::h426700d6240cdcc2
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
     8:     0x558247ee3ad5 - std::panicking::default_hook::{{closure}}::hc9a76eed0b18f82b
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
     9:     0x558247ee3789 - std::panicking::default_hook::h2e88d02087fae196
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
    10:     0x558247ee4022 - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:698:17
    11:     0x558247ee3f07 - std::panicking::begin_panic_handler::{{closure}}::he054b2a83a51d2cd
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
    12:     0x558247ee2254 - std::sys_common::backtrace::__rust_end_short_backtrace::ha48b94ab49b30915
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
    13:     0x558247ee3c39 - rust_begin_unwind
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
    14:     0x558247a65073 - core::panicking::panic_fmt::h366d3a309ae17c94
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
    15:     0x558247a65163 - core::result::unwrap_failed::hddd78f4658ac7d0f
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
    16:     0x558247a6645b - core::result::Result<T,E>::expect::h25ebf12396df4edd
    17:     0x558247a67b03 - build_script_build::main::h9eca47d65209ab16
    18:     0x558247a65f03 - core::ops::function::FnOnce::call_once::hacc4fed41162035d
    19:     0x558247a65e59 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbf661e09a84e0dc5
    20:     0x558247a67eb9 - std::rt::lang_start::{{closure}}::h258ff2399315235c
    21:     0x558247edab6e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::had4f69b3aefb47a8
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
    22:     0x558247edab6e - std::panicking::try::do_call::hf2ad5355fcafe775
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
    23:     0x558247edab6e - std::panicking::try::h0a63ac363423e61e
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
    24:     0x558247edab6e - std::panic::catch_unwind::h18088edcecb8693a
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
    25:     0x558247edab6e - std::rt::lang_start_internal::{{closure}}::ha7dad166dc711761
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
    26:     0x558247edab6e - std::panicking::try::do_call::hda0c61bf3a57d6e6
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
    27:     0x558247edab6e - std::panicking::try::hbc940e68560040a9
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
    28:     0x558247edab6e - std::panic::catch_unwind::haed0df2aeb3fa368
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
    29:     0x558247edab6e - std::rt::lang_start_internal::h9c06694362b5b80c
                                 at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
    30:     0x558247a67ea1 - std::rt::lang_start::h4ba9f6a61e20736b
    31:     0x558247a67c73 - main
    32:     0x7f3535989c87 - __libc_start_main
    33:     0x558247a6536a - _start
    34:                0x0 - <unknown>
```

**Comment by Hyaloid** [comment]
I execute run_exp_main.sh successfull after compiling TASO.
